<a href="https://colab.research.google.com/github/aayushkubb/Deep_Learning_Tutorial/blob/master/Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow

In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

2.19.0


In [5]:
# x=6
# print(x)

# Scalar Value
x_tensor=tf.constant(6)
print(x_tensor)

tf.Tensor(6, shape=(), dtype=int32)


In [7]:
y_tensor=x_tensor + 10
print(y_tensor)

tf.Tensor(16, shape=(), dtype=int32)


In [12]:
y_tensor=x_tensor + 10
y_tensor

<tf.Tensor: shape=(), dtype=int32, numpy=16>

In [8]:
x_tensor + 10

<tf.Tensor: shape=(), dtype=int32, numpy=16>

In [11]:
#typecast
"Aayush "* 2

'Aayush Aayush '

In [13]:
import tensorflow as tf

# 0D Tensor (scalar)
t0 = tf.constant(7)

# 1D Tensor (vector)
t1 = tf.constant([1, 2, 3])

# 2D Tensor (matrix)
t2 = tf.constant([[1, 2],
                  [3, 4]])

# 3D Tensor (cube / stack of matrices)
t3 = tf.constant([[[1],[2]], [[3],[4]]])

print(t0.shape, t1.shape, t2.shape, t3.shape)


() (3,) (2, 2) (2, 2, 1)


In [14]:
x = tf.constant([[1.0, 2.0],
                 [3.0, 4.0]])

y = tf.constant([[10.0, 20.0],
                 [30.0, 40.0]])


In [15]:


# Element-wise operations
print("Add:\n", x + y)
print("Multiply:\n", x * y)
print("Subtract:\n", x - y)


Add:
 tf.Tensor(
[[11. 22.]
 [33. 44.]], shape=(2, 2), dtype=float32)
Multiply:
 tf.Tensor(
[[ 10.  40.]
 [ 90. 160.]], shape=(2, 2), dtype=float32)
Subtract:
 tf.Tensor(
[[ -9. -18.]
 [-27. -36.]], shape=(2, 2), dtype=float32)


In [16]:
print("Add:\n", x + 10)

Add:
 tf.Tensor(
[[11. 12.]
 [13. 14.]], shape=(2, 2), dtype=float32)


In [17]:

# Matrix multiplication
print("MatMul:\n", tf.matmul(x, y))


MatMul:
 tf.Tensor(
[[ 70. 100.]
 [150. 220.]], shape=(2, 2), dtype=float32)


In [ ]:

# Reductions
print("Sum:", tf.reduce_sum(x))
print("Mean:", tf.reduce_mean(x))

# Reshape
print("Reshape:\n", tf.reshape(x, (4,)))


In [18]:
import tensorflow as tf

# Training data (X=inputs, y=targets)
X = tf.constant([[2.0], [4.0], [6.0], [8.0]])
y = tf.constant([[4.0], [8.0], [12.0], [16.0]])

# Trainable parameters (weights & bias)
w = tf.Variable(0.0)
b = tf.Variable(0.0)

lr = 0.01
epochs = 200

for epoch in range(epochs):
    with tf.GradientTape() as tape:
        y_pred = X * w + b
        loss = tf.reduce_mean((y - y_pred)**2)

    dw, db = tape.gradient(loss, [w, b])

    w.assign_sub(lr * dw)
    b.assign_sub(lr * db)

    if epoch % 40 == 0:
        print(f"Epoch {epoch}, Loss={loss.numpy():.4f}, w={w.numpy():.4f}, b={b.numpy():.4f}")

print("\nFinal parameters:")
print("w =", w.numpy(), " b =", b.numpy())
print("Prediction for X=10:", (10*w + b).numpy())


Epoch 0, Loss=120.0000, w=1.2000, b=0.2000
Epoch 40, Loss=0.0137, w=1.9522, b=0.2853
Epoch 80, Loss=0.0105, w=1.9580, b=0.2506
Epoch 120, Loss=0.0081, w=1.9631, b=0.2201
Epoch 160, Loss=0.0063, w=1.9676, b=0.1932

Final parameters:
w = 1.971471  b = 0.17024893
Prediction for X=10: 19.884958


In [ ]:
#KERAS
# SEQUENTIAL ->
# FUNCTIONAL ->